### ISSUE TITLE
Add board listing

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#108]
Add board listing including summary information about the boards, such as the following:
- Title
- Descriptions
- Participation: contributors, evaluators
- Most consistent hypotheses
- Overall level of disagreement
- Publication date
- Last active date (e.g., contribution and evaluation)

Board listing should also provide an ability to:
- [x] Paginated board listing
- [ ] Sort the boards
- [ ] Filter boards

To implement some of these, we'll need to calculate the board metrics ahead of time and store them in the DB or cache (or both)

**Comment by Arshitabhatt** [comment]
Hi Todd!
I would like to contribute for sorting and filtering of board listings.

**Comment by twschiller** [comment]
Great @Arshitabhatt! If you have an implementation sketch, let me know and I can take a look. I'm not sure how people typically do sorting/filtering on apps where the table isn't dynamically rendered

**Comment by Arshitabhatt** [comment]
@twschiller I have implemented the search-based filtering using JS (ReactJS) before and I am planning to work along similar direction for this.
Please have a look here : https://github.com/Arshitabhatt/readsnet-deployed
(Search strings are Delhi, Mumbai, Chennai )

**Comment by twschiller** [comment]
I don't want to introduce a React dependency as the site should ideally work without Javascript. Perhaps an approach like: https://github.com/jieter/django-tables2

**Comment by NNRepos** [comment]
hello @twschiller, i would like to contribute here, using `https://github.com/jieter/django-tables2`. are you ok with adding it as an installed app?
also, since it has built-in support for pagination, can i remove your old implementation?
thanks 😄
