### ISSUE TITLE
Automatically grab source information from URL

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#113]
Automatically grab metadata from the source URL, e.g.:
- Date published
- News source name
- Article author

We could probably grab this from the Open Graph tags on the page. We'd probably want to use Celery to run these tasks.

References:
- https://www.crummy.com/software/BeautifulSoup/
- https://github.com/erikriver/opengraph

**Comment by dip-kush** [comment]
I would like to work on this.

**Comment by twschiller** [comment]
Great! I'm going to be setting up Celery for running background tasks (hopefully later today or tomorrow). We'll probably want this feature to run as a background task when the user submits a source. 

If you wanted to get fancy, you could do it right when they paste in a source URL (similar to how Facebook and Twitter generate previews). This would probably require also writing some Javascript.

Let me know if you have any questions, or want to chat about how to best implement the feature.

**Comment by twschiller** [comment]
I've merged Celery support into the master branch. Here's some documentation about how create a task for your logic: http://docs.celeryproject.org/en/latest/userguide/tasks.html

**Comment by dip-kush** [comment]
Should I do end to end implementation for this feature in the website or just implement the Celery Task which will fetch Source URL Metadata.

**Comment by twschiller** [comment]
It would be great if you could do an end-to-end implementation. That will involve storing the meta data on the model and showing the information on the evidence page. For example, it would be good to show the article title and description in the source table instead of the URL.

Happy to look at the Celery task first if you implement it before working on the front-end
