### ISSUE TITLE
Browser extension for source clipping

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#114]
When reading the news, it's annoying to have to switch to Open Synthesis and find the relevant evidence and board for the article you're reading. Create a browser extension (e.g., in Chrome or Firefox) that allows people to submit articles as corroborating/conflicting sources for evidence. Browser extension could also alert the user when there are boards available about the topic they're reading about.

**Comment by prattheev** [comment]
@twschiller I'll take this!

**Comment by twschiller** [comment]
Great - which browser(s) did you want to work on? It'd be great if we could share code between them (e.g., Firefox, Chrome). I've done some work with Chrome extensions before, so can provide some guidance

For input, I think the two main actions are:
- Attach article as source (corroborating/conflicting) for an existing piece of evidence
- Create a new piece of evidence for a board from a corroborating source

Additionally, we might let someone save a URL / article to their account so that they can use it at a later time

Ideally a person would be able to highlight the relevant text on the page / article. But for the first pass, I think we should just focus on capturing the URL (the permanent or canonical URL, where available)

From the output, it would be good to alert the user when boards are available about the topic they're reading about. To do this, we might consider performing named entity extraction on the page content, and then perform a lookup via API call. A more private way, though, would be for the server to send over the board keywords to the client so that the client can detect matching boards without having to always send browsing activity to the server.

I can help implement API endpoints to support the the browser extension.

One more note, since people can create their own Open Synthesis deployments, it would be good to allow the user to configure which deployment to connect to (but connect to the main one by default)
