### ISSUE TITLE
Add comment spam filtering

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#122]
Flag spam comments using a service such as Akismet

References:
- https://akismet.com/
- https://github.com/mikery/django-akismet
- https://github.com/leandroarndt/djangospam

Related Issues:
- #4

**Comment by LeafyLi** [comment]
Hello, I'm a beginner, how can I help with this?

**Comment by twschiller** [comment]
Hi @LeafyLi, I'm not able to provide help on issues for at least the next month or two. But basically, this would just involve adding https://github.com/leandroarndt/djangospam and exposing the configuration options (e.g., Akismet credentials)

**Comment by LeafyLi** [comment]
Okay, I'm willing to try if that's okay.

**Comment by twschiller** [comment]
Sure, go ahead. I'll try to be responsive, but I can't prioritize this project right now. Let me know if you have any questions
