### ISSUE TITLE
Add a search box with autocomplete

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#125]
Add a board search capability using an autocomplete widget. Might search by both board name and description

References:
- https://github.com/bassjobsen/Bootstrap-3-Typeahead ([on NPM](https://www.npmjs.com/package/bootstrap-3-typeahead)) 

Related Issues:
- Board Topics: #22

**Comment by Prashant-Surya** [comment]
Can i work on this issue?

**Comment by twschiller** [comment]
Yep, that would be great. Let me know if you think we should use a widget other than the Bootstrap 3 Typeahead referenced above.

**Comment by Prashant-Surya** [comment]
I've used selectize for auto completion before. I'll use TypeAhead first, if I feel selectize is better we can discuss about that.

**Comment by Prashant-Surya** [comment]
@twschiller One doubt. Should the auto complete work for description also?

**Comment by twschiller** [comment]
Yes, I think it would be helpful if search also looked at the description. I'd probably put the hits from the board title above the hits from the description, though

**Comment by Prashant-Surya** [comment]
@twschiller can you help me with this error? jquery_post.js:1 Uncaught ReferenceError: jQuery is not defined.
Also I'm thinking to use selectize. Can you tell me which is the best way to include it in the project?

**Comment by twschiller** [comment]
Selectize looks fine. Ideally we'd find a Bootstrap 3 theme for it so it matches the rest of the interface.

For you error, have you installed the Javascript packages using NPM in your local development environment? 

    npm install
    webpack --config webpack.config.js
    python manage.py collectstatic

To install `selectize`:

    npm install selectize --save

Add it as a requirement in `assests/js/index.js`:

    require("selectize");

And then re-pack the Javascript bundle:

    webpack --config webpack.config.js

**Comment by Prashant-Surya** [comment]
Yes I installed it. Now everything is working fine, Thanks :) 
And where should I include the search box? In the board listing page? And when user selects an option from the options of selectize, user should be redirected to respective board page right?

**Comment by twschiller** [comment]
Yes, let's start with the board listing page and the homepage. In the future could consider putting it in the navbar (we need to have someone with design and UX experience review the site.

**Comment by Prashant-Surya** [comment]
Or it is better if we add in nav bar now?? So we don't need to add the same code in two places??

**Comment by twschiller** [comment]
Could you attach a picture of what it would look like in the navbar? We also need to consider how it would work on mobile devices if it's in the navbar.

Even if you put the navbar in two places, they should share the same code for fetching the results. In the base Javascript, for example, you'd just add a JQuery selector `$('.board-search').selectize(...)` to add search capabilities to whatever search boxes are on the page.

**Comment by Prashant-Surya** [comment]
In full view:
-----------------------
![web](https://cloud.githubusercontent.com/assets/5310329/19153669/122c6764-8bf5-11e6-8dd0-891063a31568.png)

In mobile view:
---------------------------
![mobile](https://cloud.githubusercontent.com/assets/5310329/19153688/24e2ab02-8bf5-11e6-92a7-a47891bad619.png)

**Comment by twschiller** [comment]
That looks pretty good, lets go with that! Will the search result dropdown work on mobile? We might need to disable it on mobile and just have a search results page once they submit their query

**Comment by Prashant-Surya** [comment]
I'll check if it is working good on mobile. If it doesn't look good we can disable it.
