### ISSUE TITLE
Refactor test suite

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#127]
The test suite is getting unwieldy:
- [ ] Figure out the proper abstractions to cut down on duplicated code. For example, it doesn't make sense to repeat the test account credentials everywhere.
- [ ] Split across multiple files

**Comment by David-Xilo** [comment]
can I give a try at this?

**Comment by twschiller** [comment]
Yep! I'm happy to give feedback on your plan/ideas for how to perform the refactoring before you start

**Comment by twschiller** [comment]
Refactored and merged into master
