### ISSUE TITLE
New user onboarding

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#132]
Provide on-boarding support to new users. For example, we could use a 'tour' which points out relevant parts of the interface. Additionally, if we add support for private boards, we could start the user out with a board that's pre-filled that they can play around with and try features on

References: 
- http://introjs.com/
- http://bootstraptour.com/

Related issues:
- #20

**Comment by lonewolf9277** [comment]
How can i start helping?

**Comment by twschiller** [comment]
Hey @lonewolf9277. I'm in the process of implementing private boards (see the branch 'private'). I've got caught up in work, but will hopefully finish writing the tests and merge this weekend. This will give us the ability to give new users pre-populated, private, boards to play around with.

Do you have any opinions around good ways to on-board?
