### ISSUE TITLE
Renew TLS certificate

### ISSUE THREAD

**Issue by jwives** [twschiller/open-synthesis#155]
Just attempted to view the site for this project and needed to switch browsers to do so; the current certificate expired 2017-05-20. Since HSTS is configured, anyone who's visited prior to the cert expiration will be unable to load the page if using Chrome, or will have to bypass warnings in other browsers.

Tangentially related to #153 I suppose?

**Comment by twschiller** [comment]
Updated cert is good until 2017-08-29
