### ISSUE TITLE
Expand the source quality evaluation using methodology by the late Dax R. Norman

### ISSUE THREAD

**Issue by no-identd** [twschiller/open-synthesis#159]
See here:

https://sites.google.com/site/daxrnorman2/analysis

The structure used there should easily transfer to Open Synthesis.

**Comment by twschiller** [comment]
Thanks, hadn't seen this method before. The method (with 15 questions) is potentially too heavy-weight to use out of the gate during ACH. Also, a few questions (e.g., was it recommended by a specialist) won't apply

If we incorporate it, we might want to target it where we get the most bang for our bug: 1) sources where there's controversy around the validity of the evidence or source, 2) linchpin pieces of evidence.
