### ISSUE TITLE
Factor in the works on SACH (Structured Analysis of Competing Hypotheses)?

### ISSUE THREAD

**Issue by no-identd** [twschiller/open-synthesis#160]
See here:

http://web.archive.org/web/20070928154654/https://www.mcmanis-monsalve.com/assets/publications/intelligence-methodology-1-07-chido.pdf

And, theoretically, the book "Structured Analysis of Competing Hypotheses Theory and Application", but it's out of print.

**Comment by twschiller** [comment]
Thanks for the reference. I think we definitely need to provide some sort of structure over the hypotheses to make evaluating and understanding the board more efficient

I need to think more about whether it makes sense to use the SACH drill-down approach, or if it makes more sense to provide some ability to indicate associates over hypotheses in a less structured way (e.g., A subsumes B, A and B are not mutually exclusive, A and B are duplicates, etc.)

SACH probably works best when everyone is working through the board in a single session. I suspect the more ad-hoc approach might be better when people are coming the board at different times.
