### ISSUE TITLE
Integrate data from OpenSources.co into source quality evaluation?

### ISSUE THREAD

**Issue by no-identd** [twschiller/open-synthesis#166]
@BigMcLargeHuge & @OpenSourcesGroup develop https://github.com/OpenSourcesGroup/opensources (see also www.opensources.co). Adding support for it should address the 'heavy-weight' drawbacks pointed out in #159.

I'll also file a separate issue with @OpenSourcesGroup to suggest leveraging Dax R. Norman's method for their database, that might hit two flies with one swat.

**Comment by no-identd** [comment]
https://github.com/OpenSourcesGroup/opensources/issues/38

**Comment by twschiller** [comment]
Thanks for raising this issue. I think integrating with a data set like this would be a good idea. It looks like the OpenSourcesGroup dataset is not being maintained, however. The last update is from April 2017

**Comment by twschiller** [comment]
Closing this issue for now. Please open a new issue if you find a better source of credibility information
