### ISSUE TITLE
410 response when accepting invitation

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#167]
Some users have been reporting a 410 response when accepting their invitation. In the admin panel, their invitation shows as accepted. The invitation add-in probably returns a 410 when a user tries to access an invitation code that's already been used.

**Comment by TrushaT** [comment]
Pls assign this issue to me I would like to work to fix this bug

**Comment by TrushaT** [comment]
Hey, @twschiller I need some guidance on some setup issues. I followed all the steps mentioned in Contribution.MD but a digest.py test is failing and if I go ahead and run Django server, after signup or login I am getting a 500 error.

`=============================================== FAILURES =============================================== 
_______________________________ DigestTests.test_can_create_first_digest _______________________________ 

self = <openach.tests.test_digest.DigestTests testMethod=test_can_create_first_digest>

    def test_can_create_first_digest(self):
        """Test that we can create a digest if the user hasn't received a digest before."""
        run_timestamp = timezone.now()
        create_board(board_title="New Board", days=-1)
        email = create_digest_email(self.daily, DigestFrequency.daily, run_timestamp)
>       self.assertListEqual(email.to, [self.daily.email])
E       AttributeError: 'NoneType' object has no attribute 'to'

openach\tests\test_digest.py:41: AttributeError
________________________ DigestTests.test_can_email_hypothesis_evidence_digest _________________________ 

self = <openach.tests.test_digest.DigestTests testMethod=test_can_email_hypothesis_evidence_digest>

    def test_can_email_hypothesis_evidence_digest(self):
        """Test that we can email a digest containing new hypotheses and evidence."""
        for x in [1, 2]:
            board = create_board(board_title="Board #{}".format(x), days=0)
            BoardFollower.objects.create(
                board=board, user=self.daily,
            )
            hypothesis = Hypothesis.objects.create(
                board=board,
                hypothesis_text="Hypothesis #{}".format(x),
                creator=self.weekly,
            )
            evidence = Evidence.objects.create(
                board=board,
                evidence_desc="Evidence #{}".format(x),
                creator=self.weekly,
            )
            notify_add(board, self.weekly, hypothesis)
            notify_add(board, self.weekly, evidence)

        succeeded, passed, failed = send_digest_emails(DigestFrequency.daily)
        self.assertEqual(succeeded, 1)
        self.assertEqual(len(mail.outbox), 1, "No digest email sent")
        txt_body = mail.outbox[0].body
        logger.info(txt_body)

        for x in [1, 2]:
            self.assertTrue("Board #{}".format(x) in txt_body)
            self.assertTrue("Hypothesis #{}".format(x) in txt_body)
>           self.assertTrue("Evidence #{}".format(x) in txt_body)
E           AssertionError: False is not true

openach\tests\test_digest.py:96: AssertionError`

**Comment by twschiller** [comment]
Sorry to hear you're hitting problems! I suspect there's an error in our env.sample file or our CONTRIBUTING.md file

I've just set up CI on GitHub actions, could you give this env options a try and let me know if you still get test errors?: http://github.com/twschiller/open-synthesis/blob/5d91c5812a5207ddfd7ad070fbcac3a5e46c49bc/.github/workflows/integration.yaml#L17-L17
