### ISSUE TITLE
Upgrade to Django 2.X

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#170]
Can run test suite with deprecation warnings on (i.e., using the `-Wd` flag) to see which features we're using have been removed.

**Known tasks:**
- [x] Convert URLs to new [simplified routing syntax](https://docs.djangoproject.com/en/2.0/releases/2.0/#simplified-url-routing-syntax)
- [x] Upgrade to use `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES`.

**References:**
* [Django 2.0 release notes](https://docs.djangoproject.com/en/2.0/releases/2.0/)
* [Features removed in Django 2.0 ](https://docs.djangoproject.com/en/2.0/releases/2.0/#features-removed-in-2-0)
* [Django deprecation timeline](https://docs.djangoproject.com/en/dev/internals/deprecation/)

**Comment by lenniezelk** [comment]
i'd like to work on this

**Comment by twschiller** [comment]
Thanks @lenniezelk, I added some notes on what this probably entails

**Comment by lenniezelk** [comment]
noted

**Comment by lenniezelk** [comment]
django-field-history does not seem to have proper django 2.0 support. Replace with django reversion?
@twschiller

**Comment by twschiller** [comment]
Does anything break when using django-field-history with 2.0? Or are you going off of the documented support? I'm wondering if it's easier to update django-field-history for 2.X instead of swapping which history library we're using

Another option is [django-simple-history](https://github.com/treyhunner/django-simple-history). Any reason to prefer [django-reversion](https://github.com/etianen/django-reversion)? The only feature we're using is the history

**Comment by lenniezelk** [comment]
i've been working on this but ran into a problem getting django-simple-history to work with tag `get_verbose_field_name` used in `openach/templates/boards/board_audit.html`. I cant seem to find fields that work on this line `{% get_verbose_field_name event.object event.field_name as field_name %}`. Any ideas @twschiller

**Comment by twschiller** [comment]
Thanks, @the-bionic. I've just migrated to Django 2.1.1
