### ISSUE TITLE
FAIL test_search.BoardSearchTests

### ISSUE THREAD

**Issue by alexandrakl** [twschiller/open-synthesis#214]
Happens when running `python manage.py test`

Prior to running `python manage.py migrate` and `python manage.py loaddata source_tags` for the first time, as according to order of steps here:
https://github.com/twschiller/open-synthesis/blob/master/CONTRIBUTING.md#local-development

Underlying cause unknown, seems to be an IntegrityError related to field_history

Attached the entire stack trace below:

![IMPORTANT_PNG](https://user-images.githubusercontent.com/15236202/81438533-f1423480-913a-11ea-9e15-6573245da20e.png)

**Comment by alexandrakl** [comment]
@twschiller Please help, I'm super new to django

**Comment by twschiller** [comment]
@alexandrakl I see the test failure too when I run it on my machine. Appears to be some shared state between tests — when I run the test by itself, it passes

I think you should be OK to continue with your setup

**Comment by twschiller** [comment]
@alexandrakl should be fixed now
