### ISSUE TITLE
Warn users before they visit a non-HTTPS source

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#25]
Warn users before the visit a non HTTPS source, as a 3rd party could then review that traffic.

**Comment by twschiller** [comment]
Hi @Antarius225, we don't use popups anywhere else in the interface yet, so would avoid that for now.  The simplest implementation would be:
- Check for an `https` schema in the URL
- Add a warning badge before the URL that says "Insecure URL"

**Comment by Nibba2018** [comment]
Hello @twschiller , I would like to work on this if it's available.
