### ISSUE TITLE
CSP Preventing captcha load in Firefox.

### ISSUE THREAD

**Issue by exinmusic** [twschiller/open-synthesis#279]
Appears there is a Content Security Problem loading the _/accounts/signup/_ captcha in Firefox.
![captcha](https://user-images.githubusercontent.com/13182222/92352135-46169d00-f092-11ea-9f41-f469eb06c41a.png)

**Comment by twschiller** [comment]
Will need to change the CSP in settings.py when captcha is enabled: https://github.com/twschiller/open-synthesis/blob/master/openintel/settings.py#L474

Interesting that Chrome isn't also blocking this

**Comment by exinmusic** [comment]
Yeah I've noticed Firefox being the picky eater between the two. Seems like Mozilla has been getting proactive in browser security, and a good bit is up to these vendors as to when they want to start enforcing new security rules in their products. 
Chrome may eventually throw similar issues if this is in fact preventing a potential for XSS.

**Comment by twschiller** [comment]
We actually set the CSP for that specific view: https://github.com/twschiller/open-synthesis/blob/master/openach/views/site.py#L113

I suspect what's happening is that Firefox doesn't support CSP entries with the path in the URL

**Comment by twschiller** [comment]
Was also impacting Chrome. I got it working by switching script-src-elem to script-src for that override. FWIW, not too worried about the CSP since that page doesn't show any user generated content
