### ISSUE TITLE
webpack setup is difficult

### ISSUE THREAD

**Issue by nnrepos** [twschiller/open-synthesis#446]
hey,
i'm trying to build the project locally (without heroku), and after running everything in the readme, i still get an error:
`Error reading C:\...\open-synthesis\webpack-stats.json. Are you sure webpack has generated the file and the path is correct?`.
wouldn't it be easier to attach a `webpack-stats.json` file for us to use, instead of building it using npm and all that stuff?
right now, as a workaround, i've disabled css and js.
thanks

**Comment by twschiller** [comment]
Hi @nnrepos, that error sounds like you might have missed the `npm run build`:

```
npm run build
python manage.py collectstatic
```

I've updated the repository to webpack 5, so you'll also want to update dependencies
