### ISSUE TITLE
Board recommendations

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#60]
Recommend boards to users based on other boards that they've viewed and/or contributed to. This could appear in multiple ways:
- For each user: "People who evaluated/viewed similar boards also viewed these recommended boards"
- For the board: "People who evaluated/viewed this board also viewed these recommended boards"

We might want to account for board quality when making recommendations.

**Comment by chrisdamba** [comment]
I'm really interested in this if that's ok?

**Comment by twschiller** [comment]
Yep, will take a look at the PR you submitted

**Comment by chrisdamba** [comment]
Thank you Todd, really appreciate the opportunity. I had initially tried to implement a custom recommender engine based off ideas from the tutorial https://github.com/jadianes/winerama-recommender-tutorial by adding an additional Cluster model and implementing the K-means clustering based recommendations. However, that turned out to be not so good as tests were failing until I decided to use the [django-recommends](http://django-recommends.readthedocs.io/en/latest/) engine. Looks ok and easy to implement.

However, a couple of things I'm not sure of. Firstly it's the UI, where do you think is best to show these recommendations and secondly, do we show the recommendations as a list or as a single item where a user can either skip or view the board, just like how the LinkedIn contact suggestion works?

**Comment by twschiller** [comment]
Overall the PR looks pretty good. I've added one question in the review (not exactly sure how code reviews work on here). Just to make sure I understand the scope/intention of the PR as I continue the review:

- This is implementing "People who evaluated/viewed similar boards also viewed these recommended boards", correct? It's not implementing "People who evaluated/viewed this board also viewed these recommended boards"? Is it possible to do both with the Python recommends library?
- Which method is it using to generate the recommendations? I don't see a call anywhere, so presumably it's the Naive algorithm as described [in the docs](https://django-recommends.readthedocs.io/en/latest/algorithms.html)?

I like the idea of showing recommendations as a list that they can choose to view or skip. Maybe support a full listing of recommended boards, but also show the best 1-3 on their profile page? The actions could be: (1) click to skip, or (2) board automatically is hidden once the user has contributed to it.

**Comment by chrisdamba** [comment]
> This is implementing "People who evaluated/viewed similar boards also viewed these recommended boards", correct? 

Yes, that's absolutely correct. As this is WIP pending feedback from reviews, I thought implementing this recommendation way would be great to get some feedback first before moving on to the next.

> It's not implementing "People who evaluated/viewed this board also viewed these recommended boards"? Is it possible to do both with the Python recommends library?

Yes, it is possible. 

The test for the first one  "People who evaluated/viewed similar boards also viewed these recommended boards" follows:

```
def test_recommendation(self):
    # test recommendations
    recommendations = self.provider.storage.get_recommendations_for_user(self.user)
    ...
```

For "People who evaluated/viewed this board also viewed these recommended boards", the test is

```
def test_similarities(self):
    # test similarities objects
    similar_to_board = self.provider.storage.get_similarities_for_object(self.board)
    ...
```

> Which method is it using to generate the recommendations? I don't see a call anywhere, so presumably it's the Naive algorithm as described in the docs?

Yes, it currently defaults to `recommends.algorithms.naive.NaiveAlgorithm` but can be changed in the `RecommendationProvider`'s `algorithm` property to use the [**`RecSysAlgorithm`**](http://django-recommends.readthedocs.io/en/latest/algorithms.html#recsysalgorithm)

> Maybe support a full listing of recommended boards, but also show the best 1-3 on their profile page? 

We could potentially show a full list but I would be inclined to think of showing the best 3 subset first and then skipping through showing the remaining items in the list as subsets is the "recommended" way (no pun intended)?

**Comment by ripsandy** [comment]
Is it open? Can I work on this?

**Comment by twschiller** [comment]
Yes, it's open. You should take a look at https://github.com/twschiller/open-synthesis/pull/151 that @chrisdamba put together. It was a work in progress, but may be a good starting point
