### ISSUE TITLE
Security scan infrastructure 

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#63]
Preliminary automatic scan with [OWASP ZAP](https://github.com/zaproxy/zaproxy) showed no major issues. However, it'd be great to have infrastructure (e.g., in Docker) for running scans regularly.

**Comment by ryrizo** [comment]
Looks like OWASP maintains a ZAP image on docker hub: https://hub.docker.com/u/owasp/. 

Here are the usage instructions - https://github.com/zaproxy/zaproxy/wiki/Docker

**Comment by twschiller** [comment]
Thanks for the info, so it's probably just a matter of dockerizing our app and configuration the application surface for OWASP then
