### ISSUE TITLE
Figure out release versioning scheme

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#64]
Figure out a release versioning/numbering scheme. Not clear if semantic versioning is a good system for a web application, though. The version numbering needs to communicate meaning to people hosting their own instance of Open Synthesis as well as programs/clients that may interact with its API in the future:
- Has an API changed (e.g., when we start supporting JSON APIs)
- Is a database migration required?
- Is the change user visible?

Considerations:
- Tracking version errors/warning in Rollbar. Config: `'code_version': git sha`

Some discussion:
- [Semantic Versioning](https://semver.org/). 
- [Semver Is Wrong For Web Applications](http://grimoire.ca/dev/webapp-versions)
- https://stackoverflow.com/questions/16826147/is-there-an-equivalent-scheme-to-semantic-versioning-for-non-api-software

**Comment by DanielHouston** [comment]
Hey Toby, I'm doing the rounds looking for interesting Hacktoberfest issues. 

Is this still relevant and a topic you'd like to explore? If so I'd be happy to help.

**Comment by twschiller** [comment]
Thanks, @DanielHouston. This issue isn't very important since we don't have an API or serve a dependency. I would focus on other areas.
