### ISSUE TITLE
Improve HTML metadata

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#70]
Page metadata should include page-specific information. This should improve SEO/discoverability.
- [x] META description tag
- [ ] META keywords tag
- [x] Open Graph tags

Ideally the keywords would be generated automatically from the board content. Alternatively, we could use the topic labels if we implement #22. As a quick alternative, we could use all the proper nouns in the title + description.

When we get a logo (see #81), the meta tags should reference the logo so they get picked up by Twitter, Facebook, etc.

**Comment by ripsandy** [comment]
Is this open too?

**Comment by twschiller** [comment]
Yes, adding tags for the keywords is still open.  I think the best way to go would be to implement #22 and use those as the keywords. That would be a language-agnostic way to implement keywords. 

Alternatively you could use a Named Entity Recognition library like NLTK or SpaCy to pull the noun phrases. We'd then want to either auto-detect the board language or set a language for the given board.
