### ISSUE TITLE
Board import/export

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#78]
Allow admins to import/export boards, e.g., using YAML. Motivation:
- Allow admins to transfer boards between instances, e.g., between a private instance and public instance.
- Create test fixtures using real data

**Comment by Jashaul** [comment]
Hey, i would like to work on this issue, could you assign it to me.

**Comment by twschiller** [comment]
Thanks @Jashaul. It's probably best to import/export using JSON instead of YAML. At some point I'll be looking to create API endpoints, so if we use JSON we'll be able to reuse what you implement for this issue.

**Comment by Jashaul** [comment]
okay sure, will work on it.
