### ISSUE TITLE
Alert admins when their deployment is outdated

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#79]
Alert admins when they need to update their Open Synthesis deployment because the software has been updated, e.g., we fixed a security bug. One reasonable approach is:
- A task runs that checks GitHub to determine the latest version and if an upgrade is required
- If an upgrade is required, an email is sent to the deployment administrator with an alert

**Comment by IanBans** [comment]
Do you mind if I give this a shot? it seems like a fairly simple issue to try out.

**Comment by twschiller** [comment]
Thanks @IanBans. I'm actually not sure how other projects implement this. Perhaps they have the server look at the version number in the `package.json`? We haven't been incrementing this version number, though
