### ISSUE TITLE
Create project branding materials

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#81]
Develop branding materials to use across the project's assets, such as:
- Logo
- FavIcon
- Color Scheme

Project assets include:
- Primary website
- Social media (e.g., Twitter, Facebook)

**Comment by mbruckert** [comment]
How is this logo:

![open synthesis-logo](https://user-images.githubusercontent.com/18492311/31856041-daf3e422-b685-11e7-84ce-ae201366f1d9.png)

**Comment by twschiller** [comment]
Thanks for the contribution, @mbruckert. Ideally the logo would convey 1) the open/cooperative nature of the tool, 2) the integration of information. That the approaches are used by some intelligence agencies isn't essential to the tool

**Comment by pwdesigns** [comment]
This looks like it's a bit stale.  Is there interest in continuing to look at this?  I'd like to contribute.

**Comment by twschiller** [comment]
Thanks, @pwdesigns! Yes, we're still looking for basic branding assets for the project. Let me know what questions you have/if you'd like to set up some time to chat

**Comment by HughEks** [comment]
@twschiller I can take the design if the issue is still open.

**Comment by twschiller** [comment]
Hi @HughEks, yes the issue is still open. Probably the right way to approach it would be to start small, e.g., 2-3 rough concepts for the logo

**Comment by royquilor** [comment]
Hi, would love to offer some designs:
1. Letters O and S combined. The S like a bolt. The O is not closed for openness
![open-synthesis-logo-1](https://user-images.githubusercontent.com/2366186/94919090-bf47bb00-04ab-11eb-9f94-6e00f8e31192.png)

2. Simple shapes with O and S in the centre with two dots for information. Or could remove the dots to simplify.
![open-synthesis-logo-2](https://user-images.githubusercontent.com/2366186/94919232-164d9000-04ac-11eb-8852-a010207aa09b.png)
