### ISSUE TITLE
Animation showing how board has changed over time

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#83]
Would be cool to build an animation showing how the board changed over time to show how the process is converging. We might even add a date slider so that the user can control the animation.

This wouldn't be too hard to do on the client side with JS. We could send the entire board history over and have the client do the number crunching

**Comment by chrisdamba** [comment]
Wouldn't mind also having a go at this.

**Comment by twschiller** [comment]
Thanks, Christopher. Do you have any ideas around how to implement this? First step would probably be making sure we're recording enough information in the DB to rebuild the entire history. I think we are with the evidence and hypotheses, but probably aren't with the votes

**Comment by chrisdamba** [comment]
Thanks for the fantastic opportunity Todd. I have D3.js visualization in mind. The general idea that I have is of a timeline/timeseries of a stacked bar chart where you can drag a particular date range to zoom (date slider as proposed), something similar to the following http://bl.ocks.org/anupsavvy/9513382 and http://bl.ocks.org/tnightingale/4718717. 

As for the board history, I agree there's need to ensure adequate data for the client. Not so sure about the appropriate visualization for this, would love to hear more of your thoughts on that.

**Comment by twschiller** [comment]
I'm not sure a stacked bar chart would be a good conceptual fit. What would the categories and axes be?

When thinking about visualizations, I generally try to think about: what kinds of question(s) should the viewer be able to answer using the visualization? A few high-level examples for ACH might be:

- What/when were the major developments that changed what conclusion you'd draw from the board?
- How has the consistency of a hypothesis evolved over time? (both by itself and relative to other hypotheses)
- If the analysts got something wrong (it was actually a hypotheses that the analysts had ruled out), how did that happen? Was there disagreement at the beginning?
- Which hypotheses/evidence are getting the most interest (evaluations) and when?

Before developing anything, I'd be happy to look at some rough mockups to see what works well vs. doesn't. The other thing to think about is that some visualization may be better for small analyst groups vs. large analyst groups (and vice versa)

**Comment by chrisdamba** [comment]
Great pointers there which I really value. I think the best way forward is generating the mockups first and then discuss if these answer the base questions you've posed above.

I think after coming up with the visualization model then we can proceed with implementing the end-point. Thanks for this feedback, really helpful!
