### ISSUE TITLE
Allow analyst to comment when assesing a hypothesis against a piece of evidence

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#84]
Add the ability for an analyst to leave a comment when evaluating a piece of evidence. (Similar to how OK Cupid allows people answering the questionnaire). This would help people understand the source of disputes and/or possible confusing evidence and hypotheses.

**Comment by Shenanigans77** [comment]
Hey @twschiller I'd like to work on this issue. I'm new to contributing to open source projects, so feedback is most welcome.

**Comment by twschiller** [comment]
No problem, @Shenanigans77. Probably the quickest way to implement would be:

* Add a text field to the Evaluation model
* On the evidence evaluation form, add a text box below each hypothesis
* On the board, include a word bubble icon in the box if there's any comments on that evidence x hypothesis. Clicking that word bubble would take user to a page with the evaluations and comments from the users

Let me know if you have any questions on how to make the change.

**Comment by Shenanigans77** [comment]
I'm running into a couple of issues setting up the environment. I can't seem to get libmemcached to work after installing. Also, when I run the command `webpack --config webpack.config.js` I get an error saying yaml can't be found. Any thoughts?

**Comment by twschiller** [comment]
Thanks, @Shenanigans77. Are you on Mac or Windows? Can you post the error messages?
- For libmemcached, have you installed it, e.g., using Homebrew if you're on Mac (`brew install libmemcached`)?
- For yaml, you might trying installing pyyaml to (`pip install pyyaml`). I don't have that installed in my environment though

**Comment by Shenanigans77** [comment]
I'm working on Windows with VS Code 
I deleted my copy of open-synthesis and started fresh, configuring according to the steps in the contributing guidelines. 

I've added the errors to a text file and included it, since they are kind of long. 
[open-synthesis-install-errors.txt](https://github.com/twschiller/open-synthesis/files/3392359/open-synthesis-install-errors.txt)

I've installed the Microsoft C++ redistributable and libmemcached, but those don't seem to be recognized. I also went through the steps to configure VS Code to use C++

**Comment by twschiller** [comment]
I'd probably just skip trying to install libmemcached on Windows. It's not necessary for the feature you're working on.
- In your .env file, set `ENABLE_CACHE=False`
- Remove the pylibmc from requirements.txt so pip doesn't try to install it

The webpack error looks like the node-gyp package is trying to run Python 2 code during installation which fails because the venv is Python 3 (notice the syntax of the `print` call in the log).  You might try looking here to see if any of these ideas work: https://spin.atomicobject.com/2019/03/27/node-gyp-windows/

**Comment by Shenanigans77** [comment]
Thanks for your help @twschiller! I've got everything set up, and now just going through and seeing how to make the change. 

As I understand the code, I'll need to make these edits in boards.py:
- On the evidence evaluation form, add a text box below each hypothesis
- On the board, include a word bubble icon in the box if there's any comments on that evidence x hypothesis. Clicking that word bubble would take user to a page with the evaluations and comments from the users

I'm still looking for where I would add the text field to the evaluation model.

**Comment by twschiller** [comment]
That's great. Take a look at `models.py:Evaluation` for storing the data. The implementation of the evaluation form is in `evaluate.html`. Let me know if you run into any more questions
