### ISSUE TITLE
Add action rate limiting

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#90]
We should implement rate limiting for certain actions to prevent spanning (e.g., login, signing, commenting, adding hypothesis, adding evidence, adding sources)

Django packages: https://djangopackages.org/grids/g/antiflood/

Need to determine the appropriate recourse for each:
- Captchas
- Disallowing the action

**Comment by VitorFalcao** [comment]
Hello @twschiller , I would like to start contributing to the project. Is this correction still needed? And should captchas be used, or should the action be disallowed?

**Comment by twschiller** [comment]
Thanks for reaching out, @VitorFalcao. I think this would still be helpful for public boards. I think it's OK to disallow the action for now, and we can add captcha support later.

Might want to dynamically adjust the rate limit based on user state? New boards will have a high rate of additions of evidence/hypothesis. Mature boards typically won't have frequent updates
