### ISSUE TITLE
Improve board history readability

### ISSUE THREAD

**Issue by twschiller** [twschiller/open-synthesis#99]
Board history was originally implemented as part of #61. However, the current history is confusing. It could be improved as follows:
- Report the initial values as their initial values, not as edits
- When evidence and hypotheses, state that they were added, not edited
- Group edits that were performed at the same time
- When evidence and hypotheses are removed, state which one was removed

Additionally it might be helpful to view the history of a particular hypothesis or piece of evidence.

**Comment by NNRepos** [comment]
in this sentence:
`When evidence and hypotheses, state that they were added, not edited`
did you mean:
`When evidence and hypotheses are added, state that they were added, not edited`?
